import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import Wrapper from "@/components/Wrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Travel Buddy",
  description: "Generated by create Travel Buudy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper />
        <Navbar />
        {children}
        <Footer />
        <Wrapper />
      </body>
    </html>
  );
}
